=== vjcspy/mgt2-example-modules/app/code/Chapter1/CustomConfig/etc/discounts.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="discounts" type="discountItems" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="discountItems">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="discount" type="discountItem" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="discountItem">
        <xs:all minOccurs="0">
            <xs:element name="name" minOccurs="0"/>
            <xs:element name="type" minOccurs="0"/>
            <xs:element name="minimum" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== vjcspy/mgt2-example-modules/app/code/Chapter1/CustomConfig/etc/discounts.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="discounts.xsd">
    <discounts>
        <discount name="free_shipping">
            <name>Free Shipping</name>
            <type>free_shipping</type>
            <minimum>100</minimum>
        </discount>
        <discount name="money_off">
            <name><![CDATA[$10 off!]]></name>
            <type>money_off</type>
            <minimum>0</minimum>
        </discount>
    </discounts>
</config>

=== vjcspy/mgt2-example-modules/app/code/Chapter1/ConfigLoadOrder/etc/discounts.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Chapter1_CustomConfig:etc/discounts.xsd">
    <discounts>
        <discount name="percent_off">
            <name>Percent Off</name>
            <type>percent_off</type>
            <minimum>20</minimum>
        </discount>
        <discount name="money_off">
            <minimum>50</minimum>
        </discount>
    </discounts>
</config>
